spring:
  application:
    name: notification-service

logging:
  level:
    root: INFO
    example.bank: DEBUG

  cloud:
    consul:
      enabled: false        # полностью отключаем Consul
      config:
        enabled: false
      discovery:
        enabled: false

  # cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
  #     enabled: true
  #     discovery:
  #       register: true
  #       prefer-ip-address: true

  # config:
  #   import: "optional:consul:/notification-service/data"

server:
  port: 8087