version: '3.9'

services:
  gateway:
    build: ./gateway-service
    container_name: bank-gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    env_file: .env
    depends_on:
      - account-service

  account-service:
    build: ./account-service
    container_name: bank-account-service
    ports:
      - "${ACCOUNT_PORT}:8081"
    env_file: .env