version: '3.9'

services:
  consul:
    image: consul:1.14
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    networks:
      - banknet

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:      
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

  cash-service:
    build: ./cash-service
    container_name: cash-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

  exchange-service:
    build: ./exchange-service
    container_name: exchange-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

  exchange-generator:
    build: ./exchange-generator
    container_name: exchange-generator
    ports:
      - "8085:8085"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

  transfer-service:
    build: ./transfer-service
    container_name: transfer-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - banknet

networks:
  banknet:
    driver: bridge