spring:
  application:
    name: exchange-service
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bank

  # cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
  #     enabled: true
  #     discovery:
  #       register: true
  #       prefer-ip-address: true

  # config:
  #   import: "optional:consul:/exchange-service/data"

  cloud:
    consul:
      enabled: false        # полностью отключаем Consul
      config:
        enabled: false
      discovery:
        enabled: false

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info

exchange:
  generator-url: http://localhost:8085/generate/rates