spring:
  application:
    name: cash-service
  # sleuth:
  #   sampler:
  #     probability: 1.0    # трассировать 100% запросов
  # zipkin:
  #   base-url: http://localhost:9411
  #   sender:
  #     type: web
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8090/realms/bank

        client:
          registration:
            cash-service-client:      # имя регистрации — можно любое понятное
              provider: keycloak
              client-id: cash-service    # этот клиент должен быть создан в Keycloak            
              client-secret: client-secret"cash-service"
              scope: openid, profile, email
              authorization-grant-type: client_credentials
          provider:
            keycloak:
              token-uri: http://localhost:8090/realms/bank/protocol/openid-connect/token
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: false
        register: true
        prefer-ip-address: true
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info