spring:
  application:
    name: transfer-service
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8090/realms/bank
        client:
          registration:
            transfer-service-client:      # имя регистрации — можно любое понятное
              provider: keycloak
              client-id: transfer-service    # этот клиент должен быть создан в Keycloak            
              client-secret: client-secret"transfer-service"      # ваш client-secret из Keycloak для transfer-service
              scope: openid, profile, email
              authorization-grant-type: client_credentials
          provider:
            keycloak:
              token-uri: http://localhost:8090/realms/bank/protocol/openid-connect/token
  cloud:
    consul:
      enabled: false        # полностью отключаем Consul
      config:
        enabled: false
      discovery:
        enabled: false

  # cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
  #     enabled: true
  #     discovery:
  #       register: true
  #       prefer-ip-address: true

  # config:
  #   import: "optional:consul:/transfer-service/data"
    
server:
  port: 8086