{
 "title": "Bank Platform - Business",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Exchange rates update delay (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - exchange_rates_last_success_timestamp_seconds{app=\"exchange-generator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfers: success vs failure",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transfer_total{app=\"transfer-service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "transfer_failed_total{app=\"transfer-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification delivery (success / failure)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(notification_sse_send_total{app=\"notification-service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(notification_sse_send_total{result=\"failure\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User logins (success)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(auth_userinfo_total{app=\"gateway-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trnsfer (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "transfer_amount_by_user_count{app=\"transfer-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposits (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(account_deposit_total{app=\"account-service\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}