apiVersion: v2
name: bank-platform
description: Umbrella chart for bank microservices (minimal)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: notification-service
    version: 0.1.0
    repository: "file://../charts/notification-service"
    condition: notificationService.enabled
  - name: postgres
    version: 0.1.0
    repository: "file://../charts/postgres"
    condition: postgres.enabled
  - name: account-service
    version: 0.1.0
    repository: "file://../charts/account-service"
    condition: accountService.enabled
  - name: cash-service
    version: 0.1.0
    repository: "file://../charts/cash-service"
    condition: cashService.enabled

  - name: gateway-service
    version: 0.1.0
    repository: "file://../charts/gateway-service"
    condition: gatewayService.enabled

  - name: exchange-service
    version: 0.1.0
    repository: "file://../charts/exchange-service"
    condition: exchangeService.enabled

  - name: exchange-generator
    version: 0.1.0
    repository: "file://../charts/exchange-generator"
    condition: exchangeGenerator.enabled

  - name: transfer-service
    version: 0.1.0
    repository: "file://../charts/transfer-service"
    condition: transferService.enabled

  - name: kaffka-service
    version: 0.1.0
    repository: "file://../charts/kaffka-service"
    condition: kaffka-service.enabled

  - name: zipkin
    version: 0.1.0
    repository: "file://../charts/zipkin"  
    condition: zipkin.enabled  

  - name: prometheus
    version: 0.1.0
    repository: "file://../charts/prometheus"  
    condition: prometheus.enabled 

  - name: grafana
    version: 0.1.0
    repository: file://../charts/grafana
    condition: grafana.enabled

  - name: elk
    version: 0.1.0
    repository: "file://../charts/elk"
    condition: elk.enabled



