FROM jenkins/inbound-agent:latest-jdk21

USER root

# Устанавливаем зависимости и утилиты
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    unzip \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

# ===== Docker CLI =====
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-26.1.3.tgz | tar xz -C /usr/local/bin --strip-components=1 docker/docker

# ===== Helm =====
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# ===== Kubectl =====
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl && mv kubectl /usr/local/bin/

# ===== Maven =====
RUN apt-get update && apt-get install -y maven

USER jenkins